apiVersion: v1
kind: ServiceAccount
metadata: 
  name: equipment-serviceaccount
  annotations: 
    azure.workload.identity/client-id: 855b9492-23c7-4d54-a82a-fa2cb0f15dd9
  labels: 
    azure.workload.identity/use: "true"